# Categorización de Variables

In [900]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import funpymodeling.exploratory as fp

In [901]:
dataset = pd.read_csv('listings - Florencia_Clean.csv')
dataset.head()

id   host_id           source                                      name  \
0  31840    380378  previous scrape          A Residenza Martin  Classic room   
1  32120     99235      city scrape        Welcome at Corte Verde in Florence   
2  32180  13925330      city scrape       Charming Gem - Oltrarno City centre   
3  39115    167739      city scrape            Central Double Shared Bathroom   
4  39165    167739  previous scrape  Florence Central Double Private Bathroom   

                                         description  \
0  Nice, private and quiet double room, classic s...   
1  Apartment at a 30 minute walk from Ponte Vecch...   
2                                                  .   
3  Double (or Twin) Room Shared Bathroom: comfort...   
4  Double room private bathroom: comfortable, lar...   

                               neighborhood_overview     host_name  \
0                                                S/D  Officina 360   
1                                                S/D         Lucia   
2                                                S/D        Cesare   
3  San Lorenzo Church, the market and Cappelle Me...       Lorenzo   
4  San Lorenzo Church, the market and Cappelle Me...       Lorenzo   

   host_since    host_location  \
0  2011-02-07  Florence, Italy   
1  2010-03-26  Florence, Italy   
2  2014-04-05  Florence, Italy   
3  2010-07-15  Florence, Italy   
4  2010-07-15  Florence, Italy   

                                          host_about  ...  \
0  360 Rentals has been offering fully furnished ...  ...   
1  I was born and raised in the beautiful Florenc...  ...   
2                                                  .  ...   
3  Casa Billi, now renewed, is centrally located ...  ...   
4  Casa Billi, now renewed, is centrally located ...  ...   

  number_of_reviews_ltm number_of_reviews_l30d review_scores_rating  \
0                   5.0                    0.0                 4.66   
1                   1.0                    0.0                 4.88   
2                   4.0                    0.0                 4.74   
3                   8.0                    0.0                 4.53   
4                   2.0                    0.0                 4.32   

  review_scores_accuracy review_scores_cleanliness review_scores_checkin  \
0                   4.73                      4.87                  4.86   
1                   4.88                      4.88                  4.84   
2                   4.79                      4.85                  4.79   
3                   4.68                      4.60                  4.81   
4                   4.21                      4.58                  4.68   

  review_scores_communication review_scores_location review_scores_value  \
0                        4.91                   4.91                4.70   
1                        4.96                   4.63                4.63   
2                        4.70                   4.82                4.85   
3                        4.74                   4.90                4.55   
4                        4.63                   4.95                4.32   

  reviews_per_month  
0              0.77  
1              0.15  
2              0.21  
3              0.46  
4              0.13  

[5 rows x 50 columns]

In [902]:
# calculamos el numero total de la población "n" del dataset
dataset.info()
n = 12722

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12722 entries, 0 to 12721
Data columns (total 50 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   id                           12722 non-null  int64  
 1   host_id                      12722 non-null  int64  
 2   source                       12722 non-null  object 
 3   name                         12722 non-null  object 
 4   description                  12722 non-null  object 
 5   neighborhood_overview        12722 non-null  object 
 6   host_name                    12722 non-null  object 
 7   host_since                   12722 non-null  object 
 8   host_location                12722 non-null  object 
 9   host_about                   12722 non-null  object 
 10  host_response_time           12722 non-null  object 
 11  host_response_rate           12722 non-null  object 
 12  host_acceptance_rate         12722 non-null  object 
 13  host_is_superhos

In [903]:
# realizamos un analisis univariado de las variables categoricas
fp.freq_tbl(dataset)

            source  frequency  percentage  cumulative_perc
0      city scrape      11884     0.93413          0.93413
1  previous scrape        838     0.06587          1.00000

----------------------------------------------------------------

                                                    name  frequency  \
0                               In the heart of Florence         14   
1                               Camera con bagno privato          7   
2                                Santo Spirito Apartment          6   
3                            Ampia Camera Centro Storico          5   
4      Vivaldi Suite～Intimate & Luxurious Florence Ce...          5   
...                                                  ...        ...   
12488  HOLA APARTMENT (with 3 bedrooms) close citycenter          1   
12489       Grazioso appartamento in centro con terrazza          1   
12490              Room 45. Rent Room in Florence. Room1          1   
12491  Private ROOM HAPPY just 8min by tram to

# Determinacion de Clases Para Datos Agrupados

In [904]:
# corroboramos los valores nulos
nulos = dataset.isnull().sum()
nulos

id                             0
host_id                        0
source                         0
name                           0
description                    0
neighborhood_overview          0
host_name                      0
host_since                     0
host_location                  0
host_about                     0
host_response_time             0
host_response_rate             0
host_acceptance_rate           0
host_is_superhost              0
host_verifications             0
host_identity_verified         0
neighbourhood_cleansed         0
property_type                  0
room_type                      0
bathrooms_text                 0
amenities                      0
has_availability               0
first_review                   0
last_review                    0
instant_bookable               0
host_listings_count            0
host_total_listings_count      0
latitude                       0
longitude                      0
accommodates                   0
bedrooms  

### Variable ”host_response_rate”

In [905]:
# calculamos el numero total de la poblacion "n"
dataset['host_response_rate'].info()
n = 12722

<class 'pandas.core.series.Series'>
RangeIndex: 12722 entries, 0 to 12721
Series name: host_response_rate
Non-Null Count  Dtype 
--------------  ----- 
12722 non-null  object
dtypes: object(1)
memory usage: 99.5+ KB


In [906]:
# Elimina el '%' y convierte a float
dataset['host_response_rate_num'] = (
    dataset['host_response_rate']
        .replace('S/D', np.nan, regex=True)
        .str.strip()                   # elimina espacios al inicio/fin
        .str.replace('%', '', regex=True)
        .astype(float)
)

In [907]:
dataset['host_response_rate_num']
#dataset['host_response_rate_num'].describe()

0        100.0
1        100.0
2        100.0
3        100.0
4        100.0
         ...  
12717    100.0
12718      NaN
12719      NaN
12720    100.0
12721    100.0
Name: host_response_rate_num, Length: 12722, dtype: float64

In [908]:
# obtenemos el limite superior y el límite inferior de la columna objetivo
Max = dataset['host_response_rate_num'].max()
Min = dataset['host_response_rate_num'].min()
Limites = [Min, Max]
Limites

[0.0, 100.0]

In [909]:
# calculamos el rango r
R = Max - Min
R

100.0

In [910]:
# calculamos el número de intervalos de clase "ni", aplocando la regla de Sturges
ni = 1+3.32*np.log10(n)
ni

14.627123898918503

In [911]:
# calculamos el ancho del intervalo "i"
i = R/ni
i

6.8366139981485885

In [912]:
categorias = ["categoria_" + str(i) for i in range(1, len(intervalos))]

In [913]:
# categorizacion de variables
#intervalos = np.linspace(Min, Max, ni + 1)
intervalos = np.linspace(0.0, 100.0, 15)
intervalos

array([  0.        ,   7.14285714,  14.28571429,  21.42857143,
        28.57142857,  35.71428571,  42.85714286,  50.        ,
        57.14285714,  64.28571429,  71.42857143,  78.57142857,
        85.71428571,  92.85714286, 100.        ])

In [914]:
# creamos las etiquetas para los intervalos
categorias = ["categoria_" + str(i) for i in range(1, len(intervalos))]
#categorias = ["categoria1", "categoria2", "categoria3", "categoria4", "categoria5", "categoria6", "categoria7", "categoria8", "categoria9", "categoria10", "categoria11", "categoria12", "categoria13", "categoria14"]


In [915]:
# finalmente creamos las categorias en la columna numerica
dataset['host_response_rate_num'] = pd.cut(dataset['host_response_rate_num'], bins=intervalos, labels=categorias, right=False)
dataset['host_response_rate_num']


0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ... 
12717    NaN
12718    NaN
12719    NaN
12720    NaN
12721    NaN
Name: host_response_rate_num, Length: 12722, dtype: category
Categories (14, object): ['categoria_1' < 'categoria_2' < 'categoria_3' < 'categoria_4' ... 'categoria_11' < 'categoria_12' < 'categoria_13' < 'categoria_14']

### Variable "host_acceptance_rate"

In [916]:
dataset['host_acceptance_rate']

0        100%
1         25%
2         65%
3         71%
4         71%
         ... 
12717    100%
12718    100%
12719     S/D
12720     97%
12721    100%
Name: host_acceptance_rate, Length: 12722, dtype: object

### Variable “host_total_listings_count”

In [917]:
dataset['host_total_listings_count']

0        41.0
1         1.0
2         1.0
3        12.0
4        12.0
         ... 
12717     4.0
12718     1.0
12719     1.0
12720     2.0
12721    13.0
Name: host_total_listings_count, Length: 12722, dtype: float64

In [918]:
# obtenemos el limite superior y el límite inferior de la columna objetivo
Max = dataset['host_total_listings_count'].max()
Min = dataset['host_total_listings_count'].min()
Limites = [Min, Max]
Limites

[1.0, 42.0]

In [919]:
# calculamos el rango r
R = Max - Min
R

41.0

In [920]:
# calculamos el número de intervalos de clase "ni", aplocando la regla de Sturges
ni = 1+3.32*np.log10(n)
ni

14.627123898918503

In [921]:
# calculamos el ancho del intervalo "i"
i = R/ni
i

2.8030117392409215

#### Creación de Categorias a Partir de Clases

In [922]:
# categorizacion de variables
intervalos = np.linspace(1.0, 42.0, 15)
intervalos

array([ 1.        ,  3.92857143,  6.85714286,  9.78571429, 12.71428571,
       15.64285714, 18.57142857, 21.5       , 24.42857143, 27.35714286,
       30.28571429, 33.21428571, 36.14285714, 39.07142857, 42.        ])

In [923]:
categorias = ["categoria_" + str(i) for i in range(1, len(intervalos))]
categorias

['categoria_1',
 'categoria_2',
 'categoria_3',
 'categoria_4',
 'categoria_5',
 'categoria_6',
 'categoria_7',
 'categoria_8',
 'categoria_9',
 'categoria_10',
 'categoria_11',
 'categoria_12',
 'categoria_13',
 'categoria_14']

In [924]:
# finalmente creamos las categorias en la columna numerica
dataset['host_total_listings_count'] = pd.cut(dataset['host_total_listings_count'], bins=intervalos, labels=categorias, right=False)
dataset['host_total_listings_count']

0        categoria_14
1         categoria_1
2         categoria_1
3         categoria_4
4         categoria_4
             ...     
12717     categoria_2
12718     categoria_1
12719     categoria_1
12720     categoria_1
12721     categoria_5
Name: host_total_listings_count, Length: 12722, dtype: category
Categories (14, object): ['categoria_1' < 'categoria_2' < 'categoria_3' < 'categoria_4' ... 'categoria_11' < 'categoria_12' < 'categoria_13' < 'categoria_14']

### Variable “accommodates”

In [925]:
dataset['accommodates']

0        2.0
1        2.0
2        4.0
3        2.0
4        2.0
        ... 
12717    3.6
12718    6.0
12719    4.0
12720    4.0
12721    4.0
Name: accommodates, Length: 12722, dtype: float64

In [926]:
# obtenemos el limite superior y el límite inferior de la columna objetivo
Max = dataset['accommodates'].max()
Min = dataset['accommodates'].min()
Limites = [Min, Max]
Limites

[1.0, 7.0]

In [927]:
# calculamos el rango r
R = Max - Min
R

6.0

In [928]:
# calculamos el ancho del intervalo "i"
i = R/ni
i

0.4101968398889153

In [929]:
# calculamos el número de intervalos de clase "ni", aplicando la regla de Sturges
ni = 1+3.32*np.log10(n)
ni

14.627123898918503

#### Creación de Categorias a Partir de Clases

In [930]:
# categorizacion de variables
intervalos = np.linspace(1.0, 7.0, 15)
intervalos

array([1.        , 1.42857143, 1.85714286, 2.28571429, 2.71428571,
       3.14285714, 3.57142857, 4.        , 4.42857143, 4.85714286,
       5.28571429, 5.71428571, 6.14285714, 6.57142857, 7.        ])

In [931]:
# creamos las etiquetas para los intervalos
categorias = ["categoria_" + str(i) for i in range(1, len(intervalos))]
categorias

['categoria_1',
 'categoria_2',
 'categoria_3',
 'categoria_4',
 'categoria_5',
 'categoria_6',
 'categoria_7',
 'categoria_8',
 'categoria_9',
 'categoria_10',
 'categoria_11',
 'categoria_12',
 'categoria_13',
 'categoria_14']

In [932]:
# finalmente creamos las categorias en la columna numerica
dataset['accommodates'] = pd.cut(dataset['accommodates'], bins=intervalos, labels=categorias, right=False)
dataset['accommodates']

0         categoria_3
1         categoria_3
2         categoria_8
3         categoria_3
4         categoria_3
             ...     
12717     categoria_7
12718    categoria_12
12719     categoria_8
12720     categoria_8
12721     categoria_8
Name: accommodates, Length: 12722, dtype: category
Categories (14, object): ['categoria_1' < 'categoria_2' < 'categoria_3' < 'categoria_4' ... 'categoria_11' < 'categoria_12' < 'categoria_13' < 'categoria_14']

### Variable “bathrooms_text”

In [933]:
dataset['bathrooms_text']

0        1 private bath
1                1 bath
2               2 baths
3               0 baths
4        1 private bath
              ...      
12717           4 baths
12718            1 bath
12719            1 bath
12720            1 bath
12721            1 bath
Name: bathrooms_text, Length: 12722, dtype: object

#### Creación de Categorias a Partir de Clases

### Variable “beds”

In [934]:
dataset['beds']

0        1.0
1        1.0
2        4.0
3        1.0
4        1.0
        ... 
12717    4.0
12718    3.0
12719    3.0
12720    2.0
12721    2.0
Name: beds, Length: 12722, dtype: float64

In [935]:
# obtenemos el limite superior y el límite inferior de la columna objetivo
Max = dataset['beds'].max()
Min = dataset['beds'].min()
Limites = [Min, Max]
Limites

[0.0, 6.0]

In [936]:
# calculamos el rango r
R = Max - Min
R

6.0

In [937]:
# calculamos el número de intervalos de clase "ni", aplocando la regla de Sturges
ni = 1+3.32*np.log10(n)
ni

14.627123898918503

In [938]:
# calculamos el ancho del intervalo "i"
i = R/ni
i

0.4101968398889153

#### Creación de Categorias a Partir de Clases

In [939]:
# categorizacion de variables
intervalos = np.linspace(0.0, 6.0, 15)
intervalos

array([0.        , 0.42857143, 0.85714286, 1.28571429, 1.71428571,
       2.14285714, 2.57142857, 3.        , 3.42857143, 3.85714286,
       4.28571429, 4.71428571, 5.14285714, 5.57142857, 6.        ])

In [940]:
# creamos las etiquetas para los intervalos
categorias = ["categoria_" + str(i) for i in range(1, len(intervalos))]
categorias

['categoria_1',
 'categoria_2',
 'categoria_3',
 'categoria_4',
 'categoria_5',
 'categoria_6',
 'categoria_7',
 'categoria_8',
 'categoria_9',
 'categoria_10',
 'categoria_11',
 'categoria_12',
 'categoria_13',
 'categoria_14']

In [941]:
# finalmente creamos las categorias en la columna numerica
dataset['beds'] = pd.cut(dataset['beds'], bins=intervalos, labels=categorias, right=False)
dataset['beds']

0         categoria_3
1         categoria_3
2        categoria_10
3         categoria_3
4         categoria_3
             ...     
12717    categoria_10
12718     categoria_8
12719     categoria_8
12720     categoria_5
12721     categoria_5
Name: beds, Length: 12722, dtype: category
Categories (14, object): ['categoria_1' < 'categoria_2' < 'categoria_3' < 'categoria_4' ... 'categoria_11' < 'categoria_12' < 'categoria_13' < 'categoria_14']

### Variable “price”

In [942]:
dataset['price']

0         95.0
1         95.0
2        130.0
3        105.0
4        102.5
         ...  
12717    163.0
12718    199.0
12719     80.0
12720    220.0
12721    104.0
Name: price, Length: 12722, dtype: float64

In [943]:
# obtenemos el limite superior y el límite inferior de la columna objetivo
Max = dataset['price'].max()
Min = dataset['price'].min()
Limites = [Min, Max]
Limites

[10.0, 420.0]

In [944]:
# calculamos el rango r
R = Max - Min
R

410.0

In [945]:
# calculamos el número de intervalos de clase "ni", aplocando la regla de Sturges
ni = 1+3.32*np.log10(n)
ni

14.627123898918503

In [946]:
# calculamos el ancho del intervalo "i"
i = R/ni
i

28.030117392409213

#### Creación de Categorias a Partir de Clases

In [947]:
# categorizacion de variables
intervalos = np.linspace(10.0, 420.0, 15)
intervalos

array([ 10.        ,  39.28571429,  68.57142857,  97.85714286,
       127.14285714, 156.42857143, 185.71428571, 215.        ,
       244.28571429, 273.57142857, 302.85714286, 332.14285714,
       361.42857143, 390.71428571, 420.        ])

In [948]:
# creamos las etiquetas para los intervalos
categorias = ["categoria_" + str(i) for i in range(1, len(intervalos))]
categorias

['categoria_1',
 'categoria_2',
 'categoria_3',
 'categoria_4',
 'categoria_5',
 'categoria_6',
 'categoria_7',
 'categoria_8',
 'categoria_9',
 'categoria_10',
 'categoria_11',
 'categoria_12',
 'categoria_13',
 'categoria_14']

In [949]:
# finalmente creamos las categorias en la columna numerica
dataset['price'] = pd.cut(dataset['price'], bins=intervalos, labels=categorias, right=False)
dataset['price']

0        categoria_3
1        categoria_3
2        categoria_5
3        categoria_4
4        categoria_4
            ...     
12717    categoria_6
12718    categoria_7
12719    categoria_3
12720    categoria_8
12721    categoria_4
Name: price, Length: 12722, dtype: category
Categories (14, object): ['categoria_1' < 'categoria_2' < 'categoria_3' < 'categoria_4' ... 'categoria_11' < 'categoria_12' < 'categoria_13' < 'categoria_14']

### Variable “number_of_reviews_ltm"

In [950]:
dataset['number_of_reviews_ltm']

0        5.0
1        1.0
2        4.0
3        8.0
4        2.0
        ... 
12717    0.0
12718    0.0
12719    0.0
12720    0.0
12721    0.0
Name: number_of_reviews_ltm, Length: 12722, dtype: float64

In [951]:
# obtenemos el limite superior y el límite inferior de la columna objetivo
Max = dataset['number_of_reviews_ltm'].max()
Min = dataset['number_of_reviews_ltm'].min()
Limites = [Min, Max]
Limites

[0.0, 68.0]

In [952]:
# calculamos el rango r
R = Max - Min
R

68.0

In [953]:
# calculamos el número de intervalos de clase "ni", aplocando la regla de Sturges
ni = 1+3.32*np.log10(n)
ni

14.627123898918503

In [954]:
# calculamos el ancho del intervalo "i"
i = R/ni
i

4.64889751874104

#### Creación de Categorias a Partir de Clases

In [955]:
# categorizacion de variables
intervalos = np.linspace(0.0, 68.0, 15)
intervalos

array([ 0.        ,  4.85714286,  9.71428571, 14.57142857, 19.42857143,
       24.28571429, 29.14285714, 34.        , 38.85714286, 43.71428571,
       48.57142857, 53.42857143, 58.28571429, 63.14285714, 68.        ])

In [956]:
# creamos las etiquetas para los intervalos
categorias = ["categoria_" + str(i) for i in range(1, len(intervalos))]
categorias

['categoria_1',
 'categoria_2',
 'categoria_3',
 'categoria_4',
 'categoria_5',
 'categoria_6',
 'categoria_7',
 'categoria_8',
 'categoria_9',
 'categoria_10',
 'categoria_11',
 'categoria_12',
 'categoria_13',
 'categoria_14']

In [957]:
# finalmente creamos las categorias en la columna numerica
dataset['number_of_reviews_ltm'] = pd.cut(dataset['number_of_reviews_ltm'], bins=intervalos, labels=categorias, right=False)
dataset['number_of_reviews_ltm']

0        categoria_2
1        categoria_1
2        categoria_1
3        categoria_2
4        categoria_1
            ...     
12717    categoria_1
12718    categoria_1
12719    categoria_1
12720    categoria_1
12721    categoria_1
Name: number_of_reviews_ltm, Length: 12722, dtype: category
Categories (14, object): ['categoria_1' < 'categoria_2' < 'categoria_3' < 'categoria_4' ... 'categoria_11' < 'categoria_12' < 'categoria_13' < 'categoria_14']

### Variable “availability_365”

In [958]:
dataset['availability_365']

0        330
1         26
2        257
3        347
4        332
        ... 
12717    310
12718    365
12719    156
12720    364
12721    143
Name: availability_365, Length: 12722, dtype: int64

In [959]:
# obtenemos el limite superior y el límite inferior de la columna objetivo
Max = dataset['availability_365'].max()
Min = dataset['availability_365'].min()
Limites = [Min, Max]
Limites

[0, 365]

In [960]:
# calculamos el rango r
R = Max - Min
R

365

In [961]:
# calculamos el número de intervalos de clase "ni", aplocando la regla de Sturges
ni = 1+3.32*np.log10(n)
ni

14.627123898918503

In [962]:
# calculamos el ancho del intervalo "i"
i = R/ni
i

24.95364109324235

#### Creación de Categorias a Partir de Clases

In [963]:
# categorizacion de variables
intervalos = np.linspace(0, 365, 15)
intervalos

array([  0.        ,  26.07142857,  52.14285714,  78.21428571,
       104.28571429, 130.35714286, 156.42857143, 182.5       ,
       208.57142857, 234.64285714, 260.71428571, 286.78571429,
       312.85714286, 338.92857143, 365.        ])

In [964]:
# creamos las etiquetas para los intervalos
categorias = ["categoria_" + str(i) for i in range(1, len(intervalos))]
categorias

['categoria_1',
 'categoria_2',
 'categoria_3',
 'categoria_4',
 'categoria_5',
 'categoria_6',
 'categoria_7',
 'categoria_8',
 'categoria_9',
 'categoria_10',
 'categoria_11',
 'categoria_12',
 'categoria_13',
 'categoria_14']

In [965]:
# finalmente creamos las categorias en la columna numerica
dataset['availability_365'] = pd.cut(dataset['availability_365'], bins=intervalos, labels=categorias, right=False)
dataset['availability_365']

0        categoria_13
1         categoria_1
2        categoria_10
3        categoria_14
4        categoria_13
             ...     
12717    categoria_12
12718             NaN
12719     categoria_6
12720    categoria_14
12721     categoria_6
Name: availability_365, Length: 12722, dtype: category
Categories (14, object): ['categoria_1' < 'categoria_2' < 'categoria_3' < 'categoria_4' ... 'categoria_11' < 'categoria_12' < 'categoria_13' < 'categoria_14']

### Variable “number_of_reviews”

In [966]:
dataset['number_of_reviews']

0        133.0
1         26.0
2         36.0
3         79.0
4         21.0
         ...  
12717      0.0
12718      0.0
12719      0.0
12720      0.0
12721      0.0
Name: number_of_reviews, Length: 12722, dtype: float64

In [967]:
# obtenemos el limite superior y el límite inferior de la columna objetivo
Max = dataset['number_of_reviews'].max()
Min = dataset['number_of_reviews'].min()
Limites = [Min, Max]
Limites

[0.0, 207.0]

In [968]:
# calculamos el rango r
R = Max - Min
R

207.0

In [969]:
# calculamos el número de intervalos de clase "ni", aplocando la regla de Sturges
ni = 1+3.32*np.log10(n)
ni

14.627123898918503

In [970]:
# calculamos el ancho del intervalo "i"
i = R/ni
i

14.151790976167579

#### Creación de Categorias a Partir de Clases

In [971]:
# categorizacion de variables
intervalos = np.linspace(0.0, 207.0, 15)
intervalos

array([  0.        ,  14.78571429,  29.57142857,  44.35714286,
        59.14285714,  73.92857143,  88.71428571, 103.5       ,
       118.28571429, 133.07142857, 147.85714286, 162.64285714,
       177.42857143, 192.21428571, 207.        ])

In [972]:
# creamos las etiquetas para los intervalos
categorias = ["categoria_" + str(i) for i in range(1, len(intervalos))]
categorias

['categoria_1',
 'categoria_2',
 'categoria_3',
 'categoria_4',
 'categoria_5',
 'categoria_6',
 'categoria_7',
 'categoria_8',
 'categoria_9',
 'categoria_10',
 'categoria_11',
 'categoria_12',
 'categoria_13',
 'categoria_14']

In [973]:
# finalmente creamos las categorias en la columna numerica
dataset['number_of_reviews'] = pd.cut(dataset['number_of_reviews'], bins=intervalos, labels=categorias, right=False)
dataset['number_of_reviews']

0        categoria_9
1        categoria_2
2        categoria_3
3        categoria_6
4        categoria_2
            ...     
12717    categoria_1
12718    categoria_1
12719    categoria_1
12720    categoria_1
12721    categoria_1
Name: number_of_reviews, Length: 12722, dtype: category
Categories (14, object): ['categoria_1' < 'categoria_2' < 'categoria_3' < 'categoria_4' ... 'categoria_11' < 'categoria_12' < 'categoria_13' < 'categoria_14']

### Variable “review_scores_location”

In [974]:
dataset['review_scores_location']

0        4.91
1        4.63
2        4.82
3        4.90
4        4.95
         ... 
12717    4.80
12718    4.80
12719    4.80
12720    4.80
12721    4.80
Name: review_scores_location, Length: 12722, dtype: float64

In [975]:
# obtenemos el limite superior y el límite inferior de la columna objetivo
Max = dataset['review_scores_location'].max()
Min = dataset['review_scores_location'].min()
Limites = [Min, Max]
Limites

[4.12, 5.0]

In [976]:
# calculamos el rango r
R = Max - Min
R

0.8799999999999999

In [977]:
# calculamos el número de intervalos de clase "ni", aplocando la regla de Sturges
ni = 1+3.32*np.log10(n)
ni

14.627123898918503

In [978]:
# calculamos el ancho del intervalo "i"
i = R/ni
i

0.060162203183707574

#### Creación de Categorias a Partir de Clases

In [979]:
# categorizacion de variables
intervalos = np.linspace(4.12, 5.0, 15)
intervalos

array([4.12      , 4.18285714, 4.24571429, 4.30857143, 4.37142857,
       4.43428571, 4.49714286, 4.56      , 4.62285714, 4.68571429,
       4.74857143, 4.81142857, 4.87428571, 4.93714286, 5.        ])

In [980]:
# creamos las etiquetas para los intervalos
categorias = ["categoria_" + str(i) for i in range(1, len(intervalos))]
categorias

['categoria_1',
 'categoria_2',
 'categoria_3',
 'categoria_4',
 'categoria_5',
 'categoria_6',
 'categoria_7',
 'categoria_8',
 'categoria_9',
 'categoria_10',
 'categoria_11',
 'categoria_12',
 'categoria_13',
 'categoria_14']

In [981]:
# finalmente creamos las categorias en la columna numerica
dataset['review_scores_location'] = pd.cut(dataset['review_scores_location'], bins=intervalos, labels=categorias, right=False)
dataset['review_scores_location']

0        categoria_13
1         categoria_9
2        categoria_12
3        categoria_13
4        categoria_14
             ...     
12717    categoria_11
12718    categoria_11
12719    categoria_11
12720    categoria_11
12721    categoria_11
Name: review_scores_location, Length: 12722, dtype: category
Categories (14, object): ['categoria_1' < 'categoria_2' < 'categoria_3' < 'categoria_4' ... 'categoria_11' < 'categoria_12' < 'categoria_13' < 'categoria_14']

### Variable “review_scores_value”

In [982]:
dataset['review_scores_value']

0        4.70
1        4.63
2        4.85
3        4.55
4        4.32
         ... 
12717    4.70
12718    4.70
12719    4.70
12720    4.70
12721    4.70
Name: review_scores_value, Length: 12722, dtype: float64

In [983]:
# obtenemos el limite superior y el límite inferior de la columna objetivo
Max = dataset['review_scores_value'].max()
Min = dataset['review_scores_value'].min()
Limites = [Min, Max]
Limites

[3.83, 5.0]

In [984]:
# calculamos el rango r
R = Max - Min
R

1.17

In [985]:
# calculamos el número de intervalos de clase "ni", aplocando la regla de Sturges
ni = 1+3.32*np.log10(n)
ni

14.627123898918503

In [986]:
# calculamos el ancho del intervalo "i"
i = R/ni
i

0.07998838377833849

#### Creación de Categorias a Partir de Clases

In [987]:
# categorizacion de variables
intervalos = np.linspace(3.83, 5.0, 15)
intervalos

array([3.83      , 3.91357143, 3.99714286, 4.08071429, 4.16428571,
       4.24785714, 4.33142857, 4.415     , 4.49857143, 4.58214286,
       4.66571429, 4.74928571, 4.83285714, 4.91642857, 5.        ])

In [988]:
# creamos las etiquetas para los intervalos
categorias = ["categoria_" + str(i) for i in range(1, len(intervalos))]
categorias

['categoria_1',
 'categoria_2',
 'categoria_3',
 'categoria_4',
 'categoria_5',
 'categoria_6',
 'categoria_7',
 'categoria_8',
 'categoria_9',
 'categoria_10',
 'categoria_11',
 'categoria_12',
 'categoria_13',
 'categoria_14']

In [989]:
# finalmente creamos las categorias en la columna numerica
dataset['review_scores_value'] = pd.cut(dataset['review_scores_value'], bins=intervalos, labels=categorias, right=False)
dataset['review_scores_value']

0        categoria_11
1        categoria_10
2        categoria_13
3         categoria_9
4         categoria_6
             ...     
12717    categoria_11
12718    categoria_11
12719    categoria_11
12720    categoria_11
12721    categoria_11
Name: review_scores_value, Length: 12722, dtype: category
Categories (14, object): ['categoria_1' < 'categoria_2' < 'categoria_3' < 'categoria_4' ... 'categoria_11' < 'categoria_12' < 'categoria_13' < 'categoria_14']

### Variable “reviews_per_month”

In [990]:
dataset['reviews_per_month']

0        0.77
1        0.15
2        0.21
3        0.46
4        0.13
         ... 
12717    1.00
12718    1.00
12719    1.00
12720    1.00
12721    1.00
Name: reviews_per_month, Length: 12722, dtype: float64

In [991]:
# obtenemos el limite superior y el límite inferior de la columna objetivo
Max = dataset['reviews_per_month'].max()
Min = dataset['reviews_per_month'].min()
Limites = [Min, Max]
Limites

[0.01, 6.46]

In [992]:
# calculamos el rango r
R = Max - Min
R

6.45

In [993]:
# calculamos el número de intervalos de clase "ni", aplocando la regla de Sturges
ni = 1+3.32*np.log10(n)
ni

14.627123898918503

In [994]:
# calculamos el ancho del intervalo "i"
i = R/ni
i

0.44096160288058395

#### Creación de Categorias a Partir de Clases

In [995]:
# categorizacion de variables
intervalos = np.linspace(0.01, 6.46, 15)
intervalos

array([0.01      , 0.47071429, 0.93142857, 1.39214286, 1.85285714,
       2.31357143, 2.77428571, 3.235     , 3.69571429, 4.15642857,
       4.61714286, 5.07785714, 5.53857143, 5.99928571, 6.46      ])

In [996]:
# creamos las etiquetas para los intervalos
categorias = ["categoria_" + str(i) for i in range(1, len(intervalos))]
categorias

['categoria_1',
 'categoria_2',
 'categoria_3',
 'categoria_4',
 'categoria_5',
 'categoria_6',
 'categoria_7',
 'categoria_8',
 'categoria_9',
 'categoria_10',
 'categoria_11',
 'categoria_12',
 'categoria_13',
 'categoria_14']

In [997]:
# finalmente creamos las categorias en la columna numerica
dataset['reviews_per_month'] = pd.cut(dataset['reviews_per_month'], bins=intervalos, labels=categorias, right=False)
dataset['reviews_per_month']

0        categoria_2
1        categoria_1
2        categoria_1
3        categoria_1
4        categoria_1
            ...     
12717    categoria_3
12718    categoria_3
12719    categoria_3
12720    categoria_3
12721    categoria_3
Name: reviews_per_month, Length: 12722, dtype: category
Categories (14, object): ['categoria_1' < 'categoria_2' < 'categoria_3' < 'categoria_4' ... 'categoria_11' < 'categoria_12' < 'categoria_13' < 'categoria_14']

### Variable “review_scores_communication”

In [998]:
dataset['review_scores_communication']

0        4.91
1        4.96
2        4.70
3        4.74
4        4.63
         ... 
12717    4.90
12718    4.90
12719    4.90
12720    4.90
12721    4.90
Name: review_scores_communication, Length: 12722, dtype: float64

In [999]:
# obtenemos el limite superior y el límite inferior de la columna objetivo
Max = dataset['review_scores_communication'].max()
Min = dataset['review_scores_communication'].min()
Limites = [Min, Max]
Limites

[4.24, 5.0]

In [1000]:
# calculamos el rango r
R = Max - Min
R

0.7599999999999998

In [1001]:
# calculamos el número de intervalos de clase "ni", aplocando la regla de Sturges
ni = 1+3.32*np.log10(n)
ni

14.627123898918503

In [1002]:
# calculamos el ancho del intervalo "i"
i = R/ni
i

0.05195826638592926

#### Creación de Categorias a Partir de Clases

In [1003]:
# categorizacion de variables
intervalos = np.linspace(4.24, 5.0, 15)
intervalos

array([4.24      , 4.29428571, 4.34857143, 4.40285714, 4.45714286,
       4.51142857, 4.56571429, 4.62      , 4.67428571, 4.72857143,
       4.78285714, 4.83714286, 4.89142857, 4.94571429, 5.        ])

In [1004]:
# creamos las etiquetas para los intervalos
categorias = ["categoria_" + str(i) for i in range(1, len(intervalos))]
categorias

['categoria_1',
 'categoria_2',
 'categoria_3',
 'categoria_4',
 'categoria_5',
 'categoria_6',
 'categoria_7',
 'categoria_8',
 'categoria_9',
 'categoria_10',
 'categoria_11',
 'categoria_12',
 'categoria_13',
 'categoria_14']

In [1005]:
# finalmente creamos las categorias en la columna numerica
dataset['review_scores_communication'] = pd.cut(dataset['review_scores_communication'], bins=intervalos, labels=categorias, right=False)
dataset['review_scores_communication']

0        categoria_13
1        categoria_14
2         categoria_9
3        categoria_10
4         categoria_8
             ...     
12717    categoria_13
12718    categoria_13
12719    categoria_13
12720    categoria_13
12721    categoria_13
Name: review_scores_communication, Length: 12722, dtype: category
Categories (14, object): ['categoria_1' < 'categoria_2' < 'categoria_3' < 'categoria_4' ... 'categoria_11' < 'categoria_12' < 'categoria_13' < 'categoria_14']

### Variable review_scores_checkin”

In [1006]:
dataset['review_scores_checkin']

0        4.86
1        4.84
2        4.79
3        4.81
4        4.68
         ... 
12717    4.90
12718    4.90
12719    4.90
12720    4.90
12721    4.90
Name: review_scores_checkin, Length: 12722, dtype: float64

In [1007]:
# obtenemos el limite superior y el límite inferior de la columna objetivo
Max = dataset['review_scores_checkin'].max()
Min = dataset['review_scores_checkin'].min()
Limites = [Min, Max]
Limites

[4.25, 5.0]

In [1008]:
# calculamos el rango r
R = Max - Min
R

0.75

In [1009]:
# calculamos el número de intervalos de clase "ni", aplocando la regla de Sturges
ni = 1+3.32*np.log10(n)
ni

14.627123898918503

In [1010]:
# calculamos el ancho del intervalo "i"
i = R/ni
i

0.051274604986114414

#### Creación de Categorias a Partir de Clases

In [1011]:
# categorizacion de variables
intervalos = np.linspace(4.25, 5.0, 15)
intervalos

array([4.25      , 4.30357143, 4.35714286, 4.41071429, 4.46428571,
       4.51785714, 4.57142857, 4.625     , 4.67857143, 4.73214286,
       4.78571429, 4.83928571, 4.89285714, 4.94642857, 5.        ])

In [1012]:
# creamos las etiquetas para los intervalos
categorias = ["categoria_" + str(i) for i in range(1, len(intervalos))]
categorias

['categoria_1',
 'categoria_2',
 'categoria_3',
 'categoria_4',
 'categoria_5',
 'categoria_6',
 'categoria_7',
 'categoria_8',
 'categoria_9',
 'categoria_10',
 'categoria_11',
 'categoria_12',
 'categoria_13',
 'categoria_14']

In [1013]:
# finalmente creamos las categorias en la columna numerica
dataset['review_scores_checkin'] = pd.cut(dataset['review_scores_checkin'], bins=intervalos, labels=categorias, right=False)
dataset['review_scores_checkin']

0        categoria_12
1        categoria_12
2        categoria_11
3        categoria_11
4         categoria_9
             ...     
12717    categoria_13
12718    categoria_13
12719    categoria_13
12720    categoria_13
12721    categoria_13
Name: review_scores_checkin, Length: 12722, dtype: category
Categories (14, object): ['categoria_1' < 'categoria_2' < 'categoria_3' < 'categoria_4' ... 'categoria_11' < 'categoria_12' < 'categoria_13' < 'categoria_14']

### Variable “review_scores_cleanliness”

In [1014]:
dataset['review_scores_cleanliness']

0        4.87
1        4.88
2        4.85
3        4.60
4        4.58
         ... 
12717    4.80
12718    4.80
12719    4.80
12720    4.80
12721    4.80
Name: review_scores_cleanliness, Length: 12722, dtype: float64

In [1015]:
# obtenemos el limite superior y el límite inferior de la columna objetivo
Max = dataset['review_scores_cleanliness'].max()
Min = dataset['review_scores_cleanliness'].min()
Limites = [Min, Max]
Limites

[4.01, 5.0]

In [1016]:
# calculamos el rango r
R = Max - Min
R

0.9900000000000002

In [1017]:
# calculamos el número de intervalos de clase "ni", aplocando la regla de Sturges
ni = 1+3.32*np.log10(n)
ni

14.627123898918503

In [1018]:
# calculamos el ancho del intervalo "i"
i = R/ni
i

0.06768247858167104

#### Creación de Categorias a Partir de Clases

In [1019]:
# categorizacion de variables
intervalos = np.linspace(4.01, 5.0, 15)
intervalos

array([4.01      , 4.08071429, 4.15142857, 4.22214286, 4.29285714,
       4.36357143, 4.43428571, 4.505     , 4.57571429, 4.64642857,
       4.71714286, 4.78785714, 4.85857143, 4.92928571, 5.        ])

In [1020]:
# creamos las etiquetas para los intervalos
categorias = ["categoria_" + str(i) for i in range(1, len(intervalos))]
categorias

['categoria_1',
 'categoria_2',
 'categoria_3',
 'categoria_4',
 'categoria_5',
 'categoria_6',
 'categoria_7',
 'categoria_8',
 'categoria_9',
 'categoria_10',
 'categoria_11',
 'categoria_12',
 'categoria_13',
 'categoria_14']

In [1021]:
# finalmente creamos las categorias en la columna numerica
dataset['review_scores_cleanliness'] = pd.cut(dataset['review_scores_cleanliness'], bins=intervalos, labels=categorias, right=False)
dataset['review_scores_cleanliness']

0        categoria_13
1        categoria_13
2        categoria_12
3         categoria_9
4         categoria_9
             ...     
12717    categoria_12
12718    categoria_12
12719    categoria_12
12720    categoria_12
12721    categoria_12
Name: review_scores_cleanliness, Length: 12722, dtype: category
Categories (14, object): ['categoria_1' < 'categoria_2' < 'categoria_3' < 'categoria_4' ... 'categoria_11' < 'categoria_12' < 'categoria_13' < 'categoria_14']

### Variable “review_scores_accuracy”

In [1022]:
dataset['review_scores_accuracy']

0        4.73
1        4.88
2        4.79
3        4.68
4        4.21
         ... 
12717    4.80
12718    4.80
12719    4.80
12720    4.80
12721    4.80
Name: review_scores_accuracy, Length: 12722, dtype: float64

In [1023]:
# obtenemos el limite superior y el límite inferior de la columna objetivo
Max = dataset['review_scores_accuracy'].max()
Min = dataset['review_scores_accuracy'].min()
Limites = [Min, Max]
Limites

[4.15, 5.0]

In [1024]:
# calculamos el rango r
R = Max - Min
R

0.8499999999999996

In [1025]:
# calculamos el número de intervalos de clase "ni", aplocando la regla de Sturges
ni = 1+3.32*np.log10(n)
ni

14.627123898918503

In [1026]:
# calculamos el ancho del intervalo "i"
i = R/ni
i

0.058111218984262976

#### Creación de Categorias a Partir de Clases

In [1027]:
# categorizacion de variables
intervalos = np.linspace(4.15, 5.0, 15)
intervalos

array([4.15      , 4.21071429, 4.27142857, 4.33214286, 4.39285714,
       4.45357143, 4.51428571, 4.575     , 4.63571429, 4.69642857,
       4.75714286, 4.81785714, 4.87857143, 4.93928571, 5.        ])

In [1028]:
# creamos las etiquetas para los intervalos
categorias = ["categoria_" + str(i) for i in range(1, len(intervalos))]
categorias

['categoria_1',
 'categoria_2',
 'categoria_3',
 'categoria_4',
 'categoria_5',
 'categoria_6',
 'categoria_7',
 'categoria_8',
 'categoria_9',
 'categoria_10',
 'categoria_11',
 'categoria_12',
 'categoria_13',
 'categoria_14']

In [1029]:
# finalmente creamos las categorias en la columna numerica
dataset['review_scores_accuracy'] = pd.cut(dataset['review_scores_accuracy'], bins=intervalos, labels=categorias, right=False)
dataset['review_scores_accuracy']

0        categoria_10
1        categoria_13
2        categoria_11
3         categoria_9
4         categoria_1
             ...     
12717    categoria_11
12718    categoria_11
12719    categoria_11
12720    categoria_11
12721    categoria_11
Name: review_scores_accuracy, Length: 12722, dtype: category
Categories (14, object): ['categoria_1' < 'categoria_2' < 'categoria_3' < 'categoria_4' ... 'categoria_11' < 'categoria_12' < 'categoria_13' < 'categoria_14']